In [4]:
#importing depedencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
pip install yfinance

Requirement already satisfied: yfinance in c:\users\sakthi spark\anaconda3\envs\streamlitenv\lib\site-packages (1.2.0)
Requirement already satisfied: pandas>=1.3.0 in c:\users\sakthi spark\appdata\roaming\python\python313\site-packages (from yfinance) (2.2.3)
Requirement already satisfied: numpy>=1.16.5 in c:\users\sakthi spark\appdata\roaming\python\python313\site-packages (from yfinance) (2.4.2)
Requirement already satisfied: requests>=2.31 in c:\users\sakthi spark\appdata\roaming\python\python313\site-packages (from yfinance) (2.32.5)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\sakthi spark\anaconda3\envs\streamlitenv\lib\site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\sakthi spark\appdata\roaming\python\python313\site-packages (from yfinance) (4.5.0)
Requirement already satisfied: pytz>=2022.5 in c:\users\sakthi spark\appdata\roaming\python\python313\site-packages (from yfinance) (2025.1)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\sakthi spark\anaconda3\envs\streamlitenv\lib\site-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in c:\users\sakthi spark\anaconda3\envs\streamlitenv\lib\site-packages (from yfinance) (4.0.1)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\sakthi spark\appdata\roaming\python\python313\site-packages (from yfinance) (4.14.2)
Requirement already satisfied: curl_cffi<0.14,>=0.7 in c:\users\sakthi spark\anaconda3\envs\streamlitenv\lib\site-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in c:\users\sakthi spark\appdata\roaming\python\python313\site-packages (from yfinance) (5.29.5)
Requirement already satisfied: websockets>=13.0 in c:\users\sakthi spark\appdata\roaming\python\python313\site-packages (from yfinance) (15.0.1)
Requirement already satisfied: cffi>=1.12.0 in c:\users\sakthi spark\appdata\roaming\python\python313\site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in c:\users\sakthi spark\appdata\roaming\python\python313\site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2025.4.26)
Requirement already satisfied: soupsieve>1.2 in c:\users\sakthi spark\appdata\roaming\python\python313\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\sakthi spark\appdata\roaming\python\python313\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: pycparser in c:\users\sakthi spark\appdata\roaming\python\python313\site-packages (from cffi>=1.12.0->curl_cffi<0.14,>=0.7->yfinance) (2.23)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sakthi spark\appdata\roaming\python\python313\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sakthi spark\appdata\roaming\python\python313\site-packages (from pandas>=1.3.0->yfinance) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\sakthi spark\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\sakthi spark\appdata\roaming\python\python313\site-packages (from requests>=2.31->yfinance) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sakthi spark\appdata\roaming\python\python313\site-packages (from requests>=2.31->yfinance) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sakthi spark\appdata\roaming\python\python313\site-packages (from requests>=2.31->yfinance) (2.3.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
#importing yfinance
import yfinance as yf
nifty=yf.download("EURUSD=X",start="2010-01-01", interval="1d")  #National stock exchange of India
print(nifty.tail())

[*********************100%***********************]  1 of 1 completed

Price          Close      High       Low      Open   Volume
Ticker      EURUSD=X  EURUSD=X  EURUSD=X  EURUSD=X EURUSD=X
Date
2026-03-02  1.175945  1.179579  1.167283  1.176014        0
2026-03-03  1.169727  1.170713  1.153203  1.169454        0
2026-03-04  1.161224  1.165488  1.157675  1.161090        0
2026-03-05  1.163562  1.164687  1.156190  1.163521        0
2026-03-06  1.160807  1.162250  1.154761  1.160712        0

In [7]:
nifty.describe()

Price         Close         High          Low         Open   Volume
Ticker     EURUSD=X     EURUSD=X     EURUSD=X     EURUSD=X EURUSD=X
count   4211.000000  4211.000000  4211.000000  4211.000000   4211.0
mean       1.186347     1.190382     1.182147     1.186367      0.0
std        0.111483     0.112068     0.111061     0.111540      0.0
min        0.959619     0.967006     0.760572     0.959619      0.0
25%        1.098298     1.101928     1.094319     1.098213      0.0
50%        1.157943     1.161200     1.154374     1.158078      0.0
75%        1.282109     1.287559     1.276699     1.282545      0.0
max        1.484406     1.493808     1.480494     1.484296      0.0

In [8]:
nifty.tail(10)

Price          Close      High       Low      Open   Volume
Ticker      EURUSD=X  EURUSD=X  EURUSD=X  EURUSD=X EURUSD=X
Date
2026-02-23  1.183474  1.183446  1.177523  1.182984        0
2026-02-24  1.179384  1.179663  1.176734  1.179315        0
2026-02-25  1.177523  1.180791  1.177135  1.177551        0
2026-02-26  1.181516  1.183012  1.178245  1.181544        0
2026-02-27  1.180303  1.182396  1.179051  1.180345        0
2026-03-02  1.175945  1.179579  1.167283  1.176014        0
2026-03-03  1.169727  1.170713  1.153203  1.169454        0
2026-03-04  1.161224  1.165488  1.157675  1.161090        0
2026-03-05  1.163562  1.164687  1.156190  1.163521        0
2026-03-06  1.160807  1.162250  1.154761  1.160712        0

In [9]:
print(nifty.columns)

MultiIndex([( 'Close', 'EURUSD=X'),
            (  'High', 'EURUSD=X'),
            (   'Low', 'EURUSD=X'),
            (  'Open', 'EURUSD=X'),
            ('Volume', 'EURUSD=X')],
           names=['Price', 'Ticker'])

In [10]:
nifty.columns = nifty.columns.get_level_values(0)

In [12]:
print(nifty['Tomorrow'])

Date
2010-01-01    1.442398
2010-01-04    1.436596
2010-01-05    1.440403
2010-01-06    1.431803
2010-01-07    1.441109
                ...
2026-03-02    1.169727
2026-03-03    1.161224
2026-03-04    1.163562
2026-03-05    1.160807
2026-03-06         NaN
Name: Tomorrow, Length: 4211, dtype: float64

In [13]:
import yfinance as yf

nifty = yf.download("EURUSD=X", start="2010-01-01")

# flatten columns
nifty.columns = nifty.columns.get_level_values(0)

# create target
nifty['Tomorrow'] = nifty['Close'].shift(-1)

nifty['Target'] = (nifty['Tomorrow'] > nifty['Close']).astype(int)

nifty = nifty.dropna()

[*********************100%***********************]  1 of 1 completed

In [28]:
import yfinance as yf

# Define the ticker symbol
ticker_symbol = "TSLA"

# Create a Ticker object
ticker = yf.Ticker(ticker_symbol)

# Fetch historical market data
historical_data = ticker.history(period="2y")  # data for the last year
print("Historical Data:")
print(historical_data)

# Fetch basic financials
financials = ticker.financials
print("\nFinancials:")
print(financials)

# Fetch stock actions like dividends and splits
actions = ticker.actions
print("\nStock Actions:")
print(actions)

Historical Data:
                                 Open        High         Low       Close  \
Date
2024-03-07 00:00:00-05:00  174.350006  180.039993  173.699997  178.649994
2024-03-08 00:00:00-05:00  181.500000  182.729996  174.699997  175.339996
2024-03-11 00:00:00-04:00  175.449997  182.869995  174.800003  177.770004
2024-03-12 00:00:00-04:00  177.770004  179.429993  172.410004  177.539993
2024-03-13 00:00:00-04:00  173.050003  176.050003  169.149994  169.479996
...                               ...         ...         ...         ...
2026-03-02 00:00:00-05:00  390.600006  404.540009  388.250000  403.320007
2026-03-03 00:00:00-05:00  395.089996  396.339996  385.390015  392.429993
2026-03-04 00:00:00-05:00  397.850006  408.329987  394.579987  405.940002
2026-03-05 00:00:00-05:00  401.570007  408.619995  399.420013  405.549988
2026-03-06 00:00:00-05:00  398.089996  402.350006  394.209991  396.730011

                              Volume  Dividends  Stock Splits
Date
2024-03-07 00:00:00-05:00  102129000        0.0           0.0
2024-03-08 00:00:00-05:00   85544600        0.0           0.0
2024-03-11 00:00:00-04:00   85391500        0.0           0.0
2024-03-12 00:00:00-04:00   87391700        0.0           0.0
2024-03-13 00:00:00-04:00  106524500        0.0           0.0
...                              ...        ...           ...
2026-03-02 00:00:00-05:00   55088300        0.0           0.0
2026-03-03 00:00:00-05:00   62617300        0.0           0.0
2026-03-04 00:00:00-05:00   68305500        0.0           0.0
2026-03-05 00:00:00-05:00   51925900        0.0           0.0
2026-03-06 00:00:00-05:00   63870200        0.0           0.0

[501 rows x 7 columns]

Financials:
                                                      2025-12-31  \
Tax Effect Of Unusual Items                        -1.333800e+08
Tax Rate For Calcs                                  2.700000e-01
Normalized EBITDA                                   1.225800e+10
Total Unusual Items                                -4.940000e+08
Total Unusual Items Excluding Goodwill             -4.940000e+08
Net Income From Continuing Operation Net Minori...  3.794000e+09
Reconciled Depreciation                             6.148000e+09
Reconciled Cost Of Revenue                          7.773300e+10
EBITDA                                              1.176400e+10
EBIT                                                5.616000e+09
Net Interest Income                                 1.342000e+09
Interest Expense                                    3.380000e+08
Interest Income                                     1.680000e+09
Normalized Income                                   4.154620e+09
Net Income From Continuing And Discontinued Ope...  3.794000e+09
Total Expenses                                      8.997800e+10
Rent Expense Supplemental                                    NaN
Total Operating Income As Reported                  4.355000e+09
Diluted Average Shares                              3.526250e+09
Basic Average Shares                                3.224750e+09
Diluted EPS                                         1.080000e+00
Basic EPS                                           1.176525e+00
Diluted NI Availto Com Stockholders                 3.794000e+09
Average Dilution Earnings                                    NaN
Net Income Common Stockholders                      3.794000e+09
Otherunder Preferred Stock Dividend                          NaN
Net Income                                          3.794000e+09
Minority Interests                                 -6.100000e+07
Net Income Including Noncontrolling Interests       3.855000e+09
Net Income Continuous Operations                    3.855000e+09
Tax Provision                                       1.423000e+09
Pretax Income                                       5.278000e+09
Other Income Expense                               -9.130000e+08
Other Non Operating Income Expenses                -4.190000e+08
Special Income Charges                             -4.940000e+08
Restructuring And Mergern Acquisition               4.940000e+08
Net Non Operating Interest Income Expense           1.342000e+09
Interest Expense Non Operating                      3.380000e+08
Interest Income Non Operating                       1.680000e+09
Operating Income                                    4.849000e+09
Operating Expense                                   1.224500e+10
Research And Development                            6.411000e+09
Selling General And Administration                  5.834000e+09
Gross Profit                                        1.709400e+10
Cost Of Revenue                                     7.773300e+10
Total Revenue                                       9.482700e+10
Operating Revenue                                   9.482700e+10

                                                      2024-12-31  \
Tax Effect Of Unusual Items                        -1.368000e+08
Tax Rate For Calcs                                  2.000000e-01
Normalized EBITDA                                   1.539200e+10
Total Unusual Items                                -6.840000e+08
Total Unusual Items Excluding Goodwill             -6.840000e+08
Net Income From Continuing Operation Net Minori...  7.130000e+09
Reconciled Depreciation                             5.368000e+09
Reconciled Cost Of Revenue                          8.024000e+10
EBITDA                                              1.470800e+10
EBIT                                                9.340000e+09
Net Interest Income                                 1.219000e+09
Interest Expense                                    3.500000e+08
Interest Income                                     1.569000e+09
Normalized Income                                   7.677200e+09
Net Income From Continuing And Discontinued Ope...  7.130000e+09
Total Expenses                                      8.993000e+10
Rent Expense Supplemental                           1.003000e+09
Total Operating Income As Reported                  7.076000e+09
Diluted Average Shares                              3.216000e+09
Basic Average Shares                                3.216000e+09
Diluted EPS                                         2.040000e+00
Basic EPS                                           2.230000e+00
Diluted NI Availto Com Stockholders                 7.130000e+09
Average Dilution Earnings                           0.000000e+00
Net Income Common Stockholders                      7.130000e+09
Otherunder Preferred Stock Dividend                          NaN
Net Income                                          7.130000e+09
Minority Interests                                 -2.300000e+07
Net Income Including Noncontrolling Interests       7.153000e+09
Net Income Continuous Operations                    7.153000e+09
Tax Provision                                       1.837000e+09
Pretax Income                                       8.990000e+09
Other Income Expense                                1.100000e+07
Other Non Operating Income Expenses                 6.950000e+08
Special Income Charges                             -6.840000e+08
Restructuring And Mergern Acquisition               6.840000e+08
Net Non Operating Interest Income Expense           1.219000e+09
Interest Expense Non Operating                      3.500000e+08
Interest Income Non Operating                       1.569000e+09
Operating Income                                    7.760000e+09
Operating Expense                                   9.690000e+09
Research And Development                            4.540000e+09
Selling General And Administration                  5.150000e+09
Gross Profit                                        1.745000e+10
Cost Of Revenue                                     8.024000e+10
Total Revenue                                       9.769000e+10
Operating Revenue                                   9.769000e+10

                                                      2023-12-31  \
Tax Effect Of Unusual Items                         0.000000e+00
Tax Rate For Calcs                                  2.100000e-01
Normalized EBITDA                                   1.479600e+10
Total Unusual Items                                 0.000000e+00
Total Unusual Items Excluding Goodwill              0.000000e+00
Net Income From Continuing Operation Net Minori...  1.499900e+10
Reconciled Depreciation                             4.667000e+09
Reconciled Cost Of Revenue                          7.911300e+10
EBITDA                                              1.479600e+10
EBIT                                                1.012900e+10
Net Interest Income                                 9.100000e+08
Interest Expense                                    1.560000e+08
Interest Income                                     1.066000e+09
Normalized Income                                   1.499900e+10
Net Income From Continuing And Discontinued Ope...  1.499900e+10
Total Expenses                                      8.788200e+10
Rent Expense Supplemental                           1.268000e+09
Total Operating Income As Reported                  8.891000e+09
Diluted Average Shares                              3.482750e+09
Basic Average Shares                                3.173500e+09
Diluted EPS                                         4.310000e+00
Basic EPS                                           4.725697e+00
Diluted NI Availto Com Stockholders                 1.499900e+10
Average Dilution Earnings                           0.000000e+00
Net Income Common Stockholders                      1.499900e+10
Otherunder Preferred Stock Dividend                          NaN
Net Income                                          1.499900e+10
Minority Interests                                  2.500000e+07
Net Income Including Noncontrolling Interests       1.497400e+10
Net Income Continuous Operations                    1.497400e+10
Tax Provision                                      -5.001000e+09
Pretax Income                                       9.973000e+09
Other Income Expense                                1.720000e+08
Other Non Operating Income Expenses                 1.720000e+08
Special Income Charges                              0.000000e+00
Restructuring And Mergern Acquisition               0.000000e+00
Net Non Operating Interest Income Expense           9.100000e+08
Interest Expense Non Operating                      1.560000e+08
Interest Income Non Operating                       1.066000e+09
Operating Income                                    8.891000e+09
Operating Expense                                   8.769000e+09
Research And Development                            3.969000e+09
Selling General And Administration                  4.800000e+09
Gross Profit                                        1.766000e+10
Cost Of Revenue                                     7.911300e+10
Total Revenue                                       9.677300e+10
Operating Revenue                                   9.677300e+10

                                                      2022-12-31   2021-12-31
Tax Effect Of Unusual Items                        -1.408000e+07          NaN
Tax Rate For Calcs                                  8.000000e-02          NaN
Normalized EBITDA                                   1.783300e+10          NaN
Total Unusual Items                                -1.760000e+08          NaN
Total Unusual Items Excluding Goodwill             -1.760000e+08          NaN
Net Income From Continuing Operation Net Minori...  1.258300e+10          NaN
Reconciled Depreciation                             3.747000e+09          NaN
Reconciled Cost Of Revenue                          6.060900e+10          NaN
EBITDA                                              1.765700e+10          NaN
EBIT                                                1.391000e+10          NaN
Net Interest Income                                 1.060000e+08          NaN
Interest Expense                                    1.910000e+08          NaN
Interest Income                                     2.970000e+08          NaN
Normalized Income                                   1.274492e+10          NaN
Net Income From Continuing And Discontinued Ope...  1.258300e+10          NaN
Total Expenses                                      6.763000e+10          NaN
Rent Expense Supplemental                           1.509000e+09  978000000.0
Total Operating Income As Reported                  1.365600e+10          NaN
Diluted Average Shares                              3.475000e+09          NaN
Basic Average Shares                                3.130000e+09          NaN
Diluted EPS                                         3.620000e+00          NaN
Basic EPS                                           4.020000e+00          NaN
Diluted NI Availto Com Stockholders                 1.258400e+10          NaN
Average Dilution Earnings                           1.000000e+06    9000000.0
Net Income Common Stockholders                      1.258300e+10          NaN
Otherunder Preferred Stock Dividend                          NaN   -5000000.0
Net Income                                          1.258300e+10          NaN
Minority Interests                                 -4.000000e+06          NaN
Net Income Including Noncontrolling Interests       1.258700e+10          NaN
Net Income Continuous Operations                    1.258700e+10          NaN
Tax Provision                                       1.132000e+09          NaN
Pretax Income                                       1.371900e+10          NaN
Other Income Expense                               -2.190000e+08          NaN
Other Non Operating Income Expenses                -4.300000e+07          NaN
Special Income Charges                             -1.760000e+08          NaN
Restructuring And Mergern Acquisition               1.760000e+08          NaN
Net Non Operating Interest Income Expense           1.060000e+08          NaN
Interest Expense Non Operating                      1.910000e+08          NaN
Interest Income Non Operating                       2.970000e+08          NaN
Operating Income                                    1.383200e+10          NaN
Operating Expense                                   7.021000e+09          NaN
Research And Development                            3.075000e+09          NaN
Selling General And Administration                  3.946000e+09          NaN
Gross Profit                                        2.085300e+10          NaN
Cost Of Revenue                                     6.060900e+10          NaN
Total Revenue                                       8.146200e+10          NaN
Operating Revenue                                   8.146200e+10          NaN

Stock Actions:
                           Dividends  Stock Splits
Date
2020-08-31 00:00:00-04:00        0.0           5.0
2022-08-25 00:00:00-04:00        0.0           3.0

In [ ]:
# momentum trading strategies-if last 3 days returns are positive → price likely to continue upward

In [17]:
# Price return (daily percentage change)
nifty['Return'] = nifty['Close'].pct_change()
# return = close(t)-close(t-1)/close(t-1) This calculates the percentage change between today's closing price and yesterday's closing price
# Moving averages
# return = close(t)-close(t-1)-close(t-2).....close(t-5)/5   This calculates the average closing price of the last 5 days.
nifty['MA5'] = nifty['Close'].rolling(5).mean() 
nifty['MA20'] = nifty['Close'].rolling(20).mean()

# Volatility   Volatility=Std(Returnt​,Returnt−1​,Returnt−2​,...) This calculates the standard deviation of returns over the last 5 days.
#Low SD-values are close together
#high SD- Values fluctuate
nifty['Volatility'] = nifty['Return'].rolling(5).std()

# Price momentum
nifty['Momentum'] = nifty['Close'] - nifty['Close'].shift(5)

In [18]:
print(nifty['Return'])

Date
2010-01-01         NaN
2010-01-04    0.002366
2010-01-05   -0.004022
2010-01-06    0.002650
2010-01-07   -0.005971
                ...
2026-02-27   -0.001027
2026-03-02   -0.003692
2026-03-03   -0.005287
2026-03-04   -0.007269
2026-03-05    0.002013
Name: Return, Length: 4210, dtype: float64

In [21]:
print(nifty['MA5'])
print(nifty['MA20'])

Date
2010-01-01         NaN
2010-01-04         NaN
2010-01-05         NaN
2010-01-06         NaN
2010-01-07    1.438039
                ...
2026-02-27    1.180440
2026-03-02    1.178934
2026-03-03    1.177003
2026-03-04    1.173743
2026-03-05    1.170152
Name: MA5, Length: 4210, dtype: float64
Date
2010-01-01         NaN
2010-01-04         NaN
2010-01-05         NaN
2010-01-06         NaN
2010-01-07         NaN
                ...
2026-02-27    1.182783
2026-03-02    1.182335
2026-03-03    1.181828
2026-03-04    1.180808
2026-03-05    1.179978
Name: MA20, Length: 4210, dtype: float64